{ lib, ... }:

{
  # Helper function to create state management scripts
  mkStateScript = name: script: ''
    #!${lib.getExe pkgs.bash}
    # State management script for ${name}
    # This script is generated by Home Manager but manages state externally
    
    ${script}
  '';

  # Helper to create a project environment
  mkProject = { name, description ? "", packages ? [], shellHook ? "" }: {
    inherit name description packages;
    script = mkStateScript name shellHook;
  };
}
